title: "Mehrdad Zandigohar"
description: "AI + single cell genomics | scRegulate, RAGulate"
url: "https://zandigohar.github.io"
baseurl: ""             

# build
markdown: kramdown
permalink: pretty

# safe GitHub Pages plugins (optional but useful)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
