# Site settings
title: "Mehrdad's Resume"
description: "A resume for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mehrdad Zandigohar"
resume_title:                   "Computational Biologist | AI for Genomics & Drug Discovery"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mzandi2@uic.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_address:         "UIC Biomedical Engineering (MC 563), 820 S. Wood St., CSN W125"

resume_header_contact_info:     "820 S. Wood St., Chicago • mzandi2@uic.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>PhD candidate (Graduating in December) applying AI/ML to disease biology. Developed scRegulate (TF activity inference) and RAGulate (literature-guided TF validation). Collaborated with UIC/UCSF/Northwestern to uncover new fibroblast and immune cell programs in fibroid tumors, hernia fibrosis, and wound healing.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/zandigohar"
  resume_linkedin_url:          "https://www.linkedin.com/in/zandigohar/"
  resume_website_url:           "https://zandigohar.github.io/"
  resume_scholar_url:           "https://scholar.google.com/citations?user=93__-C4AAAAJ&hl=en"
  
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# to _config.yml are only recognized when the server starts
